project_id = "bztyhzakstkadnyieafv"

[functions.admin-create-user]
verify_jwt = true

[functions.send-push]
verify_jwt = true

[functions.get-vapid-public-key]
verify_jwt = false

[functions.cleanup-comprovantes]
verify_jwt = false
